export const SEED_TUTORS = [
  {
    name: 'Navin Vasudev',
    email: 'navin@tuneuptogether.org',
    instruments: ['Viola'],
    role: 'Founder',
    bio: 'Passionate about making music education accessible to every student.',
    school: 'Local High School',
    credentials: '8 years playing, NYSSMA Level 6, GWYOA 7 years, Area All-State',
    location: 'Greater New York Area',
  },
  {
    name: 'Gabe Reichgott',
    email: 'gabe@tuneuptogether.org',
    instruments: ['Trumpet'],
    role: 'Founder',
    bio: 'Trumpet player with a love for sharing music with younger students.',
    school: 'Local High School',
    credentials: '8 years playing, NYSSMA Level 4, Trumpet Section Leader, AP Music Theory',
    location: 'Greater New York Area',
  },
  {
    name: 'Dash Oke',
    email: 'dash@tuneuptogether.org',
    instruments: ['Violin'],
    role: 'Teacher',
    bio: 'Dedicated violinist committed to building strong musical foundations.',
    school: 'Local High School',
    credentials: '8 years playing, Area All-State, NYSSMA Level 5',
    location: 'Greater New York Area',
  },
  {
    name: 'Abby Choi',
    email: 'abby@tuneuptogether.org',
    instruments: ['Viola'],
    role: 'Teacher',
    bio: 'Bringing warmth and patience to every lesson.',
    school: 'Local High School',
    credentials: '8 years playing, NYSSMA Level 6, GWYOA, Area All-State',
    location: 'Greater New York Area',
  },
  {
    name: 'Hazel Kwon',
    email: 'hazel@tuneuptogether.org',
    instruments: ['Cello'],
    role: 'Teacher',
    bio: 'Experienced cellist with a gift for teaching beginners.',
    school: 'Local High School',
    credentials: '10 years playing, 4 years GWYOA, NYSSMA Level 5',
    location: 'Greater New York Area',
  },
  {
    name: 'Aaron Schwartz',
    email: 'aaron@tuneuptogether.org',
    instruments: ['Drums'],
    role: 'Teacher',
    bio: 'High-energy drum teacher focused on rhythm and creativity.',
    school: 'Local High School',
    credentials: '11 years playing, 2x Drums Section Leader, AP Music Theory, Area All-State',
    location: 'Greater New York Area',
  },
  {
    name: 'Chunghyun Kawata',
    email: 'chunghyun@tuneuptogether.org',
    instruments: ['Trumpet'],
    role: 'Teacher',
    bio: 'Helping students find their voice through trumpet.',
    school: 'Local High School',
    credentials: '11 years playing, 2x Trumpet Section Leader, AP Music Theory',
    location: 'Greater New York Area',
  },
  {
    name: 'Alice Besidski',
    email: 'alice@tuneuptogether.org',
    instruments: ['Flute'],
    role: 'Teacher',
    bio: 'Flutist passionate about teaching students of all levels.',
    school: 'Local High School',
    credentials: '8 years playing',
    location: 'Greater New York Area',
  },
  {
    name: 'Emmett Ansari',
    email: 'emmett@tuneuptogether.org',
    instruments: ['Alto Saxophone'],
    role: 'Teacher',
    bio: 'Bringing the joy of saxophone to young musicians.',
    school: 'Local High School',
    credentials: '7 years playing',
    location: 'Greater New York Area',
  },
  {
    name: 'Levent Sarayli',
    email: 'levent@tuneuptogether.org',
    instruments: ['Trumpet'],
    role: 'Teacher',
    bio: 'Dedicated to building confidence and technique in every student.',
    school: 'Local High School',
    credentials: '8 years playing',
    location: 'Greater New York Area',
  },
]
