// Real Tune Up Together roster, transcribed from the chapter's tracking sheet.
// Only fields present in that sheet are filled: name, instrument(s), and
// qualifications (→ credentials). Lessons/hours are left to be entered directly
// in Google Sheets. bio/school/location are blank until provided.
export const SEED_TUTORS = [
  { name: 'Gabe Reichgott', email: 'gabe.reichgott@tuneuptogether.org', instruments: ['Trumpet'], bio: '', school: '', location: '', credentials: '7 years playing, NYSSMA Level 4' },
  { name: 'Chunghyun Kawata', email: 'chunghyun.kawata@tuneuptogether.org', instruments: ['Trumpet'], bio: '', school: '', location: '', credentials: '10 years, 2x Trumpet Section Leader, AP Music Theory' },
  { name: 'Lev Sarayli', email: 'lev.sarayli@tuneuptogether.org', instruments: ['Trumpet'], bio: '', school: '', location: '', credentials: '' },
  { name: 'Keane Nadler', email: 'keane.nadler@tuneuptogether.org', instruments: ['Trumpet'], bio: '', school: '', location: '', credentials: '' },
  { name: 'Navin Vasudev', email: 'navin.vasudev@tuneuptogether.org', instruments: ['Viola'], bio: '', school: '', location: '', credentials: 'NYSSMA Level 6, GWYOA 7 years, Area All-State' },
  { name: 'Abigail Choi', email: 'abigail.choi@tuneuptogether.org', instruments: ['Viola'], bio: '', school: '', location: '', credentials: 'NYSSMA Level 6, GWYOA 7 years, Area All-State' },
  { name: 'Leon Luyat', email: 'leon.luyat@tuneuptogether.org', instruments: ['Clarinet'], bio: '', school: '', location: '', credentials: '' },
  { name: 'Emmett Ansari', email: 'emmett.ansari@tuneuptogether.org', instruments: ['Alto Saxophone'], bio: '', school: '', location: '', credentials: '' },
  { name: 'Ali Ziff Glueck', email: 'ali.glueck@tuneuptogether.org', instruments: ['Piano'], bio: '', school: '', location: '', credentials: '12 years playing, Faust Harrison Performance Hall performer, Valley Cottage Recital Center performer' },
  { name: 'Hazel Kwon', email: 'hazel.kwon@tuneuptogether.org', instruments: ['Cello'], bio: '', school: '', location: '', credentials: '10 years playing, 4 years GWYOA, NYSSMA Level 5' },
  { name: 'Matthew Sillitoe', email: 'matthew.sillitoe@tuneuptogether.org', instruments: ['Guitar'], bio: '', school: '', location: '', credentials: '10 years playing, Scholarship winner for Berklee summer program' },
  { name: 'Alice Besidski', email: 'alice.besidski@tuneuptogether.org', instruments: ['Flute'], bio: '', school: '', location: '', credentials: '7 years playing' },
  { name: 'Lena Svigals', email: 'lena.svigals@tuneuptogether.org', instruments: ['Flute'], bio: '', school: '', location: '', credentials: '' },
  { name: 'Dash Oke', email: 'dash.oke@tuneuptogether.org', instruments: ['Violin'], bio: '', school: '', location: '', credentials: '8 years, Area All-State, NYSSMA Level 5' },
  { name: 'Lucy', email: 'lucy@tuneuptogether.org', instruments: ['Violin'], bio: '', school: '', location: '', credentials: '8 years, Area All-State, NYSSMA Level 6' },
  { name: 'Eli', email: 'eli@tuneuptogether.org', instruments: ['Violin'], bio: '', school: '', location: '', credentials: '8 years, NYSSMA Level 5, GWYOA' },
  { name: 'Eva Sandoval', email: 'eva.sandoval@tuneuptogether.org', instruments: ['Flute'], bio: '', school: '', location: '', credentials: '8 years' },
  { name: 'Mona Frank', email: 'mona.frank@tuneuptogether.org', instruments: ['Violin'], bio: 'Chapter Founder', school: '', location: '', credentials: '8 years playing, NYSSMA Level 6 (100 four times), Area All-State, GWYOA 6 years (Concertmaster for 2 years), President of Chamber Music Club, Philadelphia International Music Festival Solo Performer' },
  { name: 'Phoebe Walker', email: 'phoebe.walker@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '8 years singing, NYSSMA 6 solo (97), NYSSMA 6 a Capella (Gold with Distinction), Area All-State qualifier' },
  { name: 'Maisie VanNess', email: 'maisie.vanness@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '9 years singing, Area All-State Chorus, NYSSMA Level 6' },
  { name: 'Henry Maass', email: 'henry.maass@tuneuptogether.org', instruments: ['Drums', 'Guitar', 'Bass'], bio: '', school: '', location: '', credentials: '8 years bass + guitar, 6 years drums, 4 years playing professional gigs, 1 year touring' },
  { name: 'Ashley Wu', email: 'ashley.wu@tuneuptogether.org', instruments: ['Violin'], bio: '', school: '', location: '', credentials: 'Private lessons throughout Elementary and Middle school. Participant in High School Orchestra.' },
  { name: 'Poem Chao', email: 'poem.chao@tuneuptogether.org', instruments: ['Piano'], bio: '', school: '', location: '', credentials: '12 years of private lessons, private recitals and gig performances, participant in Jazz Band and prior accompanist for theater arts program' },
  { name: 'Lillian Maltby', email: 'lillian.maltby@tuneuptogether.org', instruments: ['Clarinet'], bio: '', school: '', location: '', credentials: '9 years of playing, participant in Dobbs Ferry HS band, member of chamber music and jazz band' },
  { name: 'Kyle Hung', email: 'kyle.hung@tuneuptogether.org', instruments: ['Piano'], bio: '', school: '', location: '', credentials: 'NYSSMA Level 6 (100), 10 years' },
  { name: 'Dominick Stern', email: 'dominick.stern@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '10+ years vocal experience, NYU Steinhardt voice training, Green Room 42 NYC Cabaret performer, NYSSMA All County and Area All-State performer' },
  { name: 'Kennedy Collins', email: 'kennedy.collins@tuneuptogether.org', instruments: ['Viola'], bio: '', school: '', location: '', credentials: 'NYSSMA Level 6 (100), 8 years experience, private lessons, GWYOA, all county principal, school orchestra, Frenchwoods Symphony Orchestra (Side by Side NY POPS), Excelsior Symphony Orchestra' },
  { name: 'Lawrence Szczeszynski', email: 'lawrence.szczeszynski@tuneuptogether.org', instruments: ['Piano'], bio: '', school: '', location: '', credentials: '13+ years of lessons' },
  { name: 'Neko Curtis', email: 'neko.curtis@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '8 years singing, Assistant director for youth theater productions, Highest level vocal program at Broadway Training Center of Westchester, school chorus' },
  { name: 'Chella Galletta', email: 'chella.galletta@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '8 years singing, Octet singing group, NYSSMA 6 a Capella (Gold with Distinction)' },
  { name: 'Lily Golub', email: 'lily.golub@tuneuptogether.org', instruments: ['Violin'], bio: '', school: '', location: '', credentials: '13 years playing, NYSSMA, all county orchestra, GWYOA for 5 years, chamber group for 4 years, Kinhaven music camp' },
  { name: 'Julia Szczeszynski', email: 'julia.szczeszynski@tuneuptogether.org', instruments: ['Piano'], bio: '', school: '', location: '', credentials: '10 years of private lesson experience, Royal Conservatory, NYSSMA Level 6 (3 years)' },
  { name: 'Jules Hagstrom', email: 'jules.hagstrom@tuneuptogether.org', instruments: ['Upright Bass', 'Guitar'], bio: '', school: '', location: '', credentials: 'Bass: 8 years in school orchestra, 1 year in Jazz Forum Youth Ensemble. Guitar: 4 years experience, 3 years in Jazz Forum Youth Ensemble, 1 year in School of Rock, 1 year in a separate band, private lessons taken throughout.' },
  { name: 'Delaney Gomez', email: 'delaney.gomez@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '10 years in school, All County Chorus Freshman year' },
  { name: 'Yael Klein', email: 'yael.klein@tuneuptogether.org', instruments: ['Voice'], bio: '', school: '', location: '', credentials: '9 years singing, in a Capella group (Octet), years of vocal lessons' },
]
